# Reference: https://github.com/i3/i3/blob/next/etc/config

# Mouse follows focus when focused monitor changes
on-focused-monitor-changed = ['move-mouse monitor-lazy-center']

[mode.main.binding]
    # See: https://nikitabobko.github.io/AeroSpace/goodies#open-a-new-window-with-applescript
    ctrl-enter = '''exec-and-forget osascript -e '
    tell application "iTerm2"
        create window with default profile
    end tell'
    '''

    # i3 wraps focus by default
    ctrl-h =         'focus --boundaries all-monitors-outer-frame left'
    ctrl-j =         'focus --boundaries all-monitors-outer-frame down'
    ctrl-k =         'focus --boundaries all-monitors-outer-frame up'
    ctrl-l = 'focus --boundaries all-monitors-outer-frame right'

    ctrl-shift-h = 'move left'
    ctrl-shift-j = 'move down'
    ctrl-shift-k = 'move up'
    ctrl-shift-l = 'move right'

    # Consider using 'join-with' command as a 'split' replacement if you want to enable
    # normalizations
    # ctrl-h = 'join-with right'
    # ctrl-v = 'join-with down'

    ctrl-f = 'fullscreen'

    ctrl-s = 'layout v_accordion' # 'layout stacking' in i3
    ctrl-w = 'layout h_accordion' # 'layout tabbed' in i3
    ctrl-e = 'layout tiles horizontal vertical' # 'layout toggle split' in i3

    ctrl-shift-space = 'layout floating tiling' # 'floating toggle' in i3

    # Not supported, because this command is redundant in AeroSpace mental model.
    # See: https://nikitabobko.github.io/AeroSpace/guide#floating-windows
    #ctrl-space = 'focus toggle_tiling_floating'

    # `focus parent`/`focus child` are not yet supported, and it's not clear whether they
    # should be supported at all https://github.com/nikitabobko/AeroSpace/issues/5
    # ctrl-a = 'focus parent'

    ctrl-1 = 'workspace 1'
    ctrl-2 = 'workspace 2'
    ctrl-3 = 'workspace 3'
    ctrl-4 = 'workspace 4'
    ctrl-5 = 'workspace 5'
    ctrl-6 = 'workspace 6'
    ctrl-7 = 'workspace 7'
    ctrl-8 = 'workspace 8'
    ctrl-9 = 'workspace 9'
    ctrl-0 = 'workspace 10'

    ctrl-shift-1 = 'move-node-to-workspace 1'
    ctrl-shift-2 = 'move-node-to-workspace 2'
    ctrl-shift-3 = 'move-node-to-workspace 3'
    ctrl-shift-4 = 'move-node-to-workspace 4'
    ctrl-shift-5 = 'move-node-to-workspace 5'
    ctrl-shift-6 = 'move-node-to-workspace 6'
    ctrl-shift-7 = 'move-node-to-workspace 7'
    ctrl-shift-8 = 'move-node-to-workspace 8'
    ctrl-shift-9 = 'move-node-to-workspace 9'
    ctrl-shift-0 = 'move-node-to-workspace 10'

    ctrl-shift-r = 'reload-config'

    ctrl-shift-q = 'close --quit-if-last-window'

    ctrl-r = 'mode resize'

[mode.resize.binding]
    h = 'resize width -50'
    j = 'resize height +50'
    k = 'resize height -50'
    l = 'resize width +50'
    enter = 'mode main'
    esc = 'mode main'

[workspace-to-monitor-force-assignment]
    1 = 1
    2 = 2
    3 = 3
    4 = 1
    5 = 2
    6 = 3
    7 = 1
    8 = 2
    9 = 3
