$terminal = kitty
$fileManager = dolphin
$menu = hyprlauncher

exec-once = waybar
exec-once = hyprpaper
exec-once = hypridle

env = XCURSOR_SIZE,24
env = HYPRCURSOR_SIZE,24
env = QT_QPA_PLATFORM=wayland

cursor {
    no_hardware_cursors = true
}

input {
    touchpad {
	natural_scroll = true
	clickfinger_behavior = true
    }
}

source = ~/.config/hypr/monitors.conf
source = ~/.config/hypr/binds.conf
source = ~/.config/hypr/style.conf
