$terminal = kitty
$fileManager = dolphin
$menu = hyprlauncher

env = XCURSOR_SIZE,24
env = HYPRCURSOR_SIZE,24
env = QT_QPA_PLATFORM=wayland

cursor {
    no_hardware_cursors = true
}

input {
    touchpad {
	natural_scroll = true
	clickfinger_behavior = true
    }

    numlock_by_default = true

    sensitivity = -0.7
}

dwindle {
    force_split = 2
}

scrolling {
    column_width = 1.0
    direction = down
}

source = ~/.config/hypr/monitors.conf
source = ~/.config/hypr/binds.conf
source = ~/.config/hypr/style.conf

exec-once = waybar
exec-once = hyprpaper
exec-once = hypridle

exec-once = [workspace 1] cider
exec-once = [workspace 2] firefox
