general {
    lock_cmd = pidof hyprlock || hyprlock       # avoid starting multiple hyprlock instances.
}

listener {
    timeout = 900
    on-timeout = ~/.config/hypr/dpms.sh off
    on-resume = ~/.config/hypr/dpms.sh on
}
