$ultrawide = desc:LG Electronics LG ULTRAWIDE 408NTVS5J487
$left = desc:ViewSonic Corporation VA2756-UHD VYP252100731
$vertical = desc:AOC U2790B 0x0000834F
$top = desc:ViewSonic Corporation VA2756-UHD VYP252100727

monitor = $ultrawide, 3440x1440@100, 0x0, 1
monitor = $left, 3840x2160@60, auto-left, 1.5
monitor = $vertical, 3840x2160@60, auto-right, 1.5, transform, 3
monitor = $top, 3840x2160@60, auto-up, 1.5

workspace = 1, monitor:$left, default:true
workspace = 2, monitor:$ultrawide, default:true
workspace = 3, monitor:$vertical, default:true
workspace = 4, monitor:$top, default:true
workspace=  5, monitor:$left
workspace = 6, monitor:$ultrawide
workspace = 7, monitor:$vertical
workspace = 8, monitor:$top
