# Disable specific steps - same options as the command line flag
disable = ["containers"]

# Do not ask to retry failed steps (default: false)
no_retry = true

# Cleanup temporary or old files
cleanup = true

skip_notify = true
display_preamble = false

[git]
# Additional git repositories to pull
repos = [
    "~/scripts"
]
